@startuml

package User {
  actor PM as PM
  actor RD as RD
}
package "Ticket: Feature Request" {
  usecase "Create" as FRCreate
  usecase "Edit" as FREdit
  usecase "Delete" as FRDelete
  usecase "Resolve" as FResolve
}
package User {
  actor QA as QA
  actor RD as RD
}
package "Ticket: Bug" {
  usecase "Create" as BugCreate
  usecase "Edit" as BugEdit
  usecase "Delete" as BugDelete
  usecase "Resolve" as BugResolve
}

QA --> BugCreate
QA --> BugEdit
QA --> BugDelete
PM --> FRCreate
PM --> FREdit
PM --> FRDelete
RD --> BugResolve
RD --> FResolve

@enduml